exports.tags = [
  {tagName: 'KID smART', tagParent: 'Client'},
  {tagName: 'NOLABA', tagParent: 'Client'},
  {tagName: 'Lutheran World Relief', tagParent: 'Client'},
  {tagName: 'Education Development Center', tagParent: 'Client'},
  {tagName: 'LifeCity', tagParent: 'Client'},
  {tagName: 'EnergyWise', tagParent: 'Client'},
  {tagName: 'Terraluna', tagParent: 'Client'},
  {tagName: 'Open Society Foundations', tagParent: 'Client'},
  {tagName: 'Trombone Shorty Foundation', tagParent: 'Client'},
  {tagName: 'Preservation Hall Foundation', tagParent: 'Client'},
  {tagName: 'Ogden Museum', tagParent: 'Client'},
  {tagName: 'Greater New Orleans Foundation', tagParent: 'Client'},
  {tagName: 'Tulane Small Center', tagParent: 'Client'},
  {tagName: 'N.O. Arts Education Alliance', tagParent: 'Client'},
  {tagName: 'Tulane Taylor Center', tagParent: 'Client'},
  {tagName: 'Operation Spark', tagParent: 'Client'},
  {tagName: '4.0 Schools', tagParent: 'Client'},
  {tagName: 'Global Integrity', tagParent: 'Client'},
  {tagName: 'The Data Center', tagParent: 'Client'},

  {tagName: 'Context & Background', tagParent: 'Section'},
  {tagName: 'Approach', tagParent: 'Section'},
  {tagName: 'Goals', tagParent: 'Section'},
  {tagName: 'Scope of Work', tagParent: 'Section'},
  {tagName: 'Activities', tagParent: 'Section'},
  {tagName: 'Deliverables', tagParent: 'Section'},
  {tagName: 'Consultant Team', tagParent: 'Section'},
  {tagName: 'Budget & Schedule', tagParent: 'Section'},
  {tagName: 'Budget', tagParent: 'Section'},
  {tagName: 'Timeline', tagParent: 'Section'},

  {tagName: '2023', tagParent: 'Year'},
  {tagName: '2022', tagParent: 'Year'},
  {tagName: '2021', tagParent: 'Year'},
  {tagName: '2020', tagParent: 'Year'},
  {tagName: '2019', tagParent: 'Year'},
  {tagName: '2018', tagParent: 'Year'},
  {tagName: '2017', tagParent: 'Year'},
  {tagName: '2016', tagParent: 'Year'},
  {tagName: '2015', tagParent: 'Year'},
]